query MyQuery {
  Solana {
    DEXTradeByTokens(
      orderBy: {descendingByField: DESCFIELD }
      limit: {count: COUNT, offset: OFFSET}
      where: {
        Trade: {
          Dex: { ProtocolName: { PROTOCOLNAME} }
  			}
      }
    ) {
      Block {
        datefield: Date(interval: {in: days, count: 1 })
      }
      volume: sum(of: Trade_AmountInUSD)
      medAmt: median(of: Trade_AmountInUSD)
      lowAmt: quantile(of: Trade_AmountInUSD, level: 0.025)
      highAmt: quantile(of: Trade_AmountInUSD, level: 0.975)
      medPrice: median(of: Trade_PriceInUSD)
      lowPrice: quantile(of: Trade_PriceInUSD, level: 0.025)
      highPrice: quantile(of: Trade_PriceInUSD, level: 0.975)
      Trade {
        Currency {
          Symbol
          MintAddress
        }
        Dex {
          ProtocolName
        }
      }
      tradeCount: count(distinct: Transaction_Signature)
    }
  }
}